# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_facts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=20)),
                ('hobbies', models.CharField(max_length=20)),
                ('more_about_me', models.TextField()),
            ],
        ),
    ]
